apiVersion: v1
kind: Secret
metadata:
  name: {{ include "system-monitor-chart.fullname" . }}-secret
  labels:
    {{- include "system-monitor-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  ALERT_WEBHOOK_TOKEN: {{ .Values.secret.alertWebhookToken | quote }}
