apiVersion: v1
kind: PersistentVolume                        # Physical/actual storage resource
metadata:
  name: system-monitor-pv                      # Name of the PV
spec:
  storageClassName: ""                         # Disable dynamic provisioning matching
  capacity:
    storage: 100Mi                             # Size of the volume
  accessModes:
    - ReadWriteOnce                             # Can be mounted read-write by one node
  hostPath:
    path: /mnt/data/system-monitor             # Folder on the kind node's disk
  persistentVolumeReclaimPolicy: Retain         # Keep data even if PVC is deleted
